# Generated by Django 5.2.1 on 2025-05-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companywebsite_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='company_logo/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='company_photo/')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='companies.companymedia')),
            ],
        ),
    ]
