# Generated by Django 5.2.1 on 2025-05-19 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recruitment_type', models.CharField(max_length=200)),
                ('experience_required', models.CharField(max_length=150)),
                ('education_required', models.CharField(max_length=150)),
                ('salary_type', models.CharField(max_length=100)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpeningBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits_description', models.CharField()),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='jobs.jobopening')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='contact',
            name='job_opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='jobs.jobopening'),
        ),
    ]
