# Generated by Django 5.0.2 on 2025-05-22 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="姓名")),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="年齡")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("男", "男"), ("女", "女"), ("其他", "其他")],
                        max_length=10,
                        null=True,
                        verbose_name="性別",
                    ),
                ),
                (
                    "highest_education",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="最高學歷"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手機"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="信箱"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="地區"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="完整地址"
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="語言能力"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, null=True, verbose_name="個人簡介"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=128, verbose_name="密碼"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶",
                "verbose_name_plural": "用戶",
            },
        ),
        migrations.CreateModel(
            name="UserEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=100, verbose_name="學校名稱")),
                ("major", models.CharField(max_length=100, verbose_name="科系名稱")),
                ("degree", models.CharField(max_length=100, verbose_name="學位")),
                ("start_date", models.DateField(verbose_name="開始日期")),
                ("end_date", models.DateField(verbose_name="結束日期")),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "advisor",
                    models.CharField(blank=True, max_length=100, verbose_name="指導教授"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "教育經歷",
                "verbose_name_plural": "教育經歷",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="專案名稱")),
                ("description", models.TextField(verbose_name="專案描述")),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True, upload_to="project_covers/", verbose_name="封面圖片"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "technologies",
                    models.CharField(blank=True, max_length=200, verbose_name="使用技術"),
                ),
                ("url", models.URLField(blank=True, verbose_name="專案連結")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "專案經歷",
                "verbose_name_plural": "專案經歷",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=100, verbose_name="技能名稱")),
                ("proficiency", models.IntegerField(default=0, verbose_name="熟練度")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶技能",
                "verbose_name_plural": "用戶技能",
            },
        ),
        migrations.CreateModel(
            name="UserWorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100, verbose_name="公司名稱")),
                ("title", models.CharField(max_length=100, verbose_name="職稱")),
                ("start_date", models.DateField(verbose_name="開始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="是否為現職"),
                ),
                ("description", models.TextField(verbose_name="工作描述")),
                ("work_type", models.CharField(max_length=50, verbose_name="工作類型")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "工作經歷",
                "verbose_name_plural": "工作經歷",
                "ordering": ["-start_date"],
            },
        ),
    ]
