# Generated by Django 5.0.2 on 2025-05-22 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userproject",
            options={"verbose_name": "專案經歷", "verbose_name_plural": "專案經歷"},
        ),
        migrations.RemoveField(
            model_name="userproject",
            name="description",
        ),
        migrations.RemoveField(
            model_name="userproject",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="userproject",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="userproject",
            name="technologies",
        ),
        migrations.RemoveField(
            model_name="userproject",
            name="url",
        ),
    ]
