# Generated by Django 5.0.2 on 2025-05-22 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userproject_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usereducation",
            name="advisor",
        ),
        migrations.RemoveField(
            model_name="userworkexperience",
            name="is_current",
        ),
        migrations.RemoveField(
            model_name="userworkexperience",
            name="work_type",
        ),
    ]
