# Generated by Django 5.0.2 on 2025-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="icon_svg",
            field=models.TextField(blank=True, null=True, verbose_name="技能圖標SVG"),
        ),
    ]
