# Generated by Django 5.0.2 on 2025-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userskill_icon_svg"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproject",
            name="technologies",
            field=models.JSONField(
                default=list, help_text="包含技術名稱和圖標的列表", verbose_name="使用技術"
            ),
        ),
    ]
