# Generated by Django 5.0.2 on 2025-05-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_userproject_technologies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="技術名稱"),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="technology_icons/", verbose_name="技術圖標"
                    ),
                ),
            ],
            options={
                "verbose_name": "技術圖標",
                "verbose_name_plural": "技術圖標",
            },
        ),
        migrations.RemoveField(
            model_name="userproject",
            name="technologies",
        ),
        migrations.AddField(
            model_name="userproject",
            name="technologies",
            field=models.ManyToManyField(to="users.technology", verbose_name="使用技術"),
        ),
    ]
