# Generated by Django 5.0.2 on 2025-05-26 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_technology_remove_userproject_technologies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userproject",
            name="technologies",
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
