# Generated by Django 5.0.2 on 2025-05-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_userproject_technologies_delete_technology"),
    ]

    operations = [
        migrations.AddField(
            model_name="usereducation",
            name="school_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="school_images/", verbose_name="學校照片"
            ),
        ),
    ]
