# Generated by Django 5.0.2 on 2025-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_usereducation_school_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userworkexperience",
            options={
                "ordering": ["-end_date"],
                "verbose_name": "工作經歷",
                "verbose_name_plural": "工作經歷",
            },
        ),
        migrations.AddField(
            model_name="userworkexperience",
            name="company_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_images/", verbose_name="公司照片"
            ),
        ),
        migrations.AlterField(
            model_name="userworkexperience",
            name="title",
            field=models.CharField(max_length=100, verbose_name="職位名稱"),
        ),
    ]
