# Generated by Django 5.2.1 on 2025-05-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companywebsite_contact'),
        ('jobs', '0002_contact_jobopening_jobopeningbenefit_delete_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='jobopeningbenefit',
            name='benefits_description',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
