# Generated by Django 5.2.1 on 2025-05-24 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_jobopening_salary_max_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_job_openings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
