# Generated by Django 5.0.2 on 2025-05-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_jobopening_liked_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobopening", name="liked_by",),
    ]
