# Generated by Django 5.2.1 on 2025-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobopening_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='characteristics',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
