# Generated by Django 5.2.1 on 2025-05-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bg_color_hex', models.CharField(max_length=7)),
                ('industry', models.CharField(max_length=100)),
                ('industry_description', models.TextField()),
                ('capital', models.IntegerField()),
                ('employees', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits_description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='companies.company')),
            ],
        ),
    ]
