# Generated by Django 5.2.1 on 2025-05-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=255)),
                ('benefit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='companies.companybenefit')),
            ],
        ),
        migrations.CreateModel(
            name='StatutoryBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=255)),
                ('benefit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory', to='companies.companybenefit')),
            ],
        ),
    ]
