# Generated by Django 5.2.1 on 2025-05-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_otherbenefit_statutorybenefit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
    ]
