# Generated by Django 5.2.1 on 2025-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_product',
            field=models.CharField(default='居家家具、收納用品、寢具與窗簾、生活雜貨', max_length=200),
            preserve_default=False,
        ),
    ]
