# Generated by Django 5.2.1 on 2025-05-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companymedia_companyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymedia',
            name='logo',
            field=models.FileField(upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='companyphoto',
            name='photo',
            field=models.FileField(upload_to='company_photo/'),
        ),
    ]
