# Generated by Django 5.0.2 on 2025-05-23 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0008_company_company_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="company_id",
        ),
    ]
