# Generated by Django 5.2.1 on 2025-05-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='characteristics',
            field=models.CharField(default='建築業', max_length=20),
            preserve_default=False,
        ),
    ]
