# Generated by Django 5.2.1 on 2025-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
