# Generated by Django 5.0.2 on 2025-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0011_company_isliked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymedia",
            name="logo",
            field=models.ImageField(upload_to="company_logo/", verbose_name="公司標誌"),
        ),
    ]
