# Generated by Django 5.0.2 on 2025-06-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0012_alter_companymedia_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companymedia",
            options={"verbose_name": "公司媒體", "verbose_name_plural": "公司媒體"},
        ),
        migrations.AlterField(
            model_name="companymedia",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="companies.company",
                verbose_name="公司",
            ),
        ),
    ]
